### ISSUE TITLE
Can you share your data set?

### ISSUE THREAD

**Issue by priya-dwivedi** [aneeshvartakavi/podsumm#2]
@aneeshvartakavi - Very cool work with the PodSumm paper. We are trying to do something similar and summarize webinars. Is it possible for you to share your labelled data set? The ASR text and corresponding labels for summarize or not. We could really use it to augment our existing data set.

**Comment by TDehaene** [comment]
Seconded, this dataset could help us greatly with summarizing transcriptions of audio datasets. Any sharing you could do would be greatly appreciated 🙏 !

**Comment by aneeshvartakavi** [comment]
Hi @priya-dwivedi  and @TDehaene, unfortunately we haven't been able to release the dataset yet. 

I will communicate your interest to our internal legal/IP group and will reply here if we are successful!

**Comment by HenryJunW** [comment]
Hello, impressive work! Any updates to share the dataset? Thanks in advance!

**Comment by samkoesnadi** [comment]
I read the paper and it is the goal of the PodSumm paper to have this work as a spark for future works in the field. It would make sense to publish the data set to align with this goal. The benefit that I can see for the company to it, is the public visibility that it gets for future uses by other people who refer to the dataset.

@aneeshvartakavi
